import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

// virtual:pwa-register/react is generated by vite-plugin-pwa at build time.
// Vitest does not run that plugin, so the import would fail to resolve in any
// code that calls useRegisterSW (the update banner). Resolve it to an inert
// stub here; individual tests can vi.mock() over the top to assert behavior.
const stubVirtualPWARegister = () => ({
  name: 'stub-virtual-pwa-register',
  resolveId(id: string) {
    if (id === 'virtual:pwa-register/react') return '\0virtual:pwa-register/react'
  },
  load(id: string) {
    if (id === '\0virtual:pwa-register/react') {
      return `export function useRegisterSW() {
        return {
          needRefresh: [false, () => {}],
          offlineReady: [false, () => {}],
          updateServiceWorker: async () => {},
        }
      }`
    }
  },
})

export default defineConfig({
  plugins: [react(), stubVirtualPWARegister()],
  test: {
    projects: [
      {
        extends: true,
        test: {
          name: 'unit',
          globals: true,
          environment: 'happy-dom',
          setupFiles: ['./tests/setup.unit.ts'],
          include: [
            'src/**/*.test.{ts,tsx}',
            'workers/**/src/**/*.test.ts',
            'supabase/functions/**/*.test.ts',
          ],
          css: false,
        },
      },
      {
        // Runs against the live local Supabase stack — `make start` first.
        // These do NOT mock the database on purpose: the whole point is
        // catching drift between what the app thinks the schema does and what
        // it does. Constraints, triggers and RLS policies are only really
        // tested by trying them.
        extends: true,
        test: {
          name: 'integration',
          globals: true,
          environment: 'node',
          setupFiles: ['./tests/setup.integration.ts'],
          include: ['tests/integration/**/*.test.ts'],
          testTimeout: 30_000,
          hookTimeout: 30_000,
          fileParallelism: false,
        },
      },
      {
        // Multi-step journeys rather than single rules: "the club polls, six
        // people answer, the planner picks a venue and the session moves"
        // instead of "this constraint fires".
        extends: true,
        test: {
          name: 'scenario',
          globals: true,
          environment: 'node',
          setupFiles: ['./tests/setup.integration.ts'],
          include: ['tests/scenario/**/*.test.ts'],
          testTimeout: 60_000,
          hookTimeout: 60_000,
          fileParallelism: false,
        },
      },
    ],
  },
})
